version: '3.1'

networks:
  bdd:

services:
  db: 
    image: "postgres:${POSTGRES_VERSION}"
    container_name: "postgres_DevOps"
    restart: "always"
    volumes:
    - "./bdd/persistent_volume:/var/lib/postgresql/data"
    - "./bdd/sql_file:/docker-entrypoint-initdb.d/"
    environment:
    - "POSTGRES_DB=db"
    - "POSTGRES_USER=toudard"
    - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    networks:
    - bdd
  
  java:
    build:
      context: .
      dockerfile: java.dockerfile
    image: "java-devops"
    container_name: "java_DevOps"
    restart: "always"
    environment:
    - "SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}"
    networks: 
    - bdd
  
  httpd:
    build:
      context: .
      dockerfile: httpd.dockerfile
    image: "httpd-devops"
    container_name: "httpd_DevOps"
    restart: "always"
    ports:
    - "80:80"
    networks: 
    - bdd